name: WildFly Cloud Tests

on:
  schedule:
    - cron: '45 11 * * *'
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runtimeImage:
        description: 'Name/tag of the base runtime image'
        required: false
      base64EncodedEnvVars:
        # We are doing this because there is a max of 10 inputs on GH Actions
        description: 'Env vars (one per line) encoded with base64'
        required: false

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
#  kubernetes-jdk11:
#    if: ${{!github.event.inputs.runtimeImage}}
#    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
#    with:
#      runtimeImage: quay.io/wildfly/wildfly-runtime:latest-jdk11
#      type: Kubernetes
#  openshift-jdk11:
#    if: ${{!github.event.inputs.runtimeImage}}
#    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
#    with:
#      runtimeImage: quay.io/wildfly/wildfly-runtime:latest-jdk11
#      type: Openshift

  kubernetes-jdk17:
    if: ${{!github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: quay.io/wildfly/wildfly-runtime:latest-jdk17
      type: Kubernetes
#  openshift-jdk17:
#    if: ${{!github.event.inputs.runtimeImage}}
#    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
#    with:
#      runtimeImage: quay.io/wildfly/wildfly-runtime:latest-jdk17
#      type: Openshift

  kubernetes-jdk21:
    if: ${{!github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: quay.io/wildfly/wildfly-runtime:latest-jdk21
      type: Kubernetes
#  openshift-jdk21:
#    if: ${{!github.event.inputs.runtimeImage}}
#    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
#    with:
#      runtimeImage: quay.io/wildfly/wildfly-runtime:latest-jdk21
#      type: Openshift

  # Custom image jobs
  kubernetes-custom-image:
    if: ${{github.event.inputs.runtimeImage}}
    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
    with:
      runtimeImage: ${{github.event.inputs.runtimeImage}}
      type: Kubernetes
      base64EncodedEnvVars: ${{github.event.inputs.base64EncodedEnvVars}}
#  openshift-custom-image:
#    if: ${{github.event.inputs.runtimeImage}}
#    uses: ./.github/workflows/wildfly-cloud-tests-callable.yml
#    with:
#      runtimeImage: ${{github.event.inputs.runtimeImage}}
#      type: Openshift
#      base64EncodedEnvVars: ${{github.event.inputs.base64EncodedEnvVars}}
